default_region      = "japaneast"
prefix              = "xiao"
padding             = "002"
environment         = "dev"
resource_group_name = "rg-xiao-dev-002"
app_insights_name   = "appin-xiao-dev-001"